# Generated by Django 5.0.3 on 2024-03-20 19:01
def gestion(apps,schemas_migration):
    Group=apps.get_model('auth','Group')
    Permission=apps.get_model('auth','Permission')
    taskteam=Group(name='taskteam')
    taskteam.save()

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunPython(gestion)
    ]
